# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import route_trust_pb2 as route__trust__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in route_trust_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrustEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateRoute = channel.unary_unary(
                '/route_trust.TrustEngine/ValidateRoute',
                request_serializer=route__trust__pb2.RouteRequest.SerializeToString,
                response_deserializer=route__trust__pb2.TrustReply.FromString,
                _registered_method=True)


class TrustEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrustEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateRoute,
                    request_deserializer=route__trust__pb2.RouteRequest.FromString,
                    response_serializer=route__trust__pb2.TrustReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'route_trust.TrustEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('route_trust.TrustEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrustEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/route_trust.TrustEngine/ValidateRoute',
            route__trust__pb2.RouteRequest.SerializeToString,
            route__trust__pb2.TrustReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
