# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: route_trust.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'route_trust.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11route_trust.proto\x12\x0broute_trust\"s\n\x0cRouteRequest\x12\x16\n\x0eprefix_address\x18\x01 \x01(\t\x12\x15\n\rprefix_length\x18\x02 \x01(\r\x12\x10\n\x08peer_asn\x18\x03 \x01(\r\x12\x0f\n\x07\x61s_path\x18\x04 \x03(\r\x12\x11\n\trouter_id\x18\x05 \x01(\t\"K\n\nTrustReply\x12\x10\n\x08is_legit\x18\x01 \x01(\x08\x12\x1b\n\x13trust_score_penalty\x18\x02 \x01(\x02\x12\x0e\n\x06reason\x18\x03 \x01(\t2T\n\x0bTrustEngine\x12\x45\n\rValidateRoute\x12\x19.route_trust.RouteRequest\x1a\x17.route_trust.TrustReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_trust_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTEREQUEST']._serialized_start=34
  _globals['_ROUTEREQUEST']._serialized_end=149
  _globals['_TRUSTREPLY']._serialized_start=151
  _globals['_TRUSTREPLY']._serialized_end=226
  _globals['_TRUSTENGINE']._serialized_start=228
  _globals['_TRUSTENGINE']._serialized_end=312
# @@protoc_insertion_point(module_scope)
